import {test,expect} from '@playwright/test';

test('real contact trajectories replace local material owners in the dressed canonical body',async({page,request})=>{
  const response=await request.get('/api/body/experiments/garment-contact');expect(response.ok()).toBeTruthy();
  const data=await response.json(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await expect(page.locator('#model')).toHaveValue('ihm-body');
  await expect(page.locator('#garment-shirt')).toBeChecked();await expect(page.locator('#garment-shorts')).toBeChecked();
  await page.locator('#regional-study').selectOption('garment-contact');
  await expect(page.locator('#garment-contact-monitor')).toBeVisible();
  await expect(page.locator('#regional-note')).toContainText('49 recorded snapshots');
  await expect(page.locator('#time')).toHaveAttribute('max','48');
  await expect(page.locator('#time-value')).toHaveText('0.000 s');
  await expect(page.locator('#trajectory-run')).toBeDisabled();
  await expect(page.locator('#trajectory-run')).toHaveValue('garment-contact');
  await page.locator('#variable').selectOption('Panel contact resultant');
  await page.locator('#time').fill('7');await page.locator('#time').dispatchEvent('input');
  const force=Math.hypot(...data.panel.contact_force_n[7].reduce((sum,v)=>sum.map((x,k)=>x+v[k]),[0,0,0]));
  await expect(page.locator('#time-value')).toHaveText('0.035 s');
  await expect(page.locator('#chart .chart-values strong')).toHaveText(force.toPrecision(5));
  await expect(page.locator('#garment-contact-selected')).toContainText(force.toPrecision(5));
  await expect(page.locator('#flow-legend')).toContainText('containment unvalidated');
  await page.locator('#garment-contact-focus').click();
  await page.screenshot({path:'test-results/garment-contact-dressed.png',fullPage:true});
  await page.locator('#systems input[type="checkbox"][value="integumentary"]').uncheck();
  await page.locator('.view-section').filter({has:page.locator('#clothing-components')}).evaluate(el=>el.open=true);
  await page.locator('#garment-shorts').uncheck();
  await page.locator('#time').fill('48');await page.locator('#time').dispatchEvent('input');
  await expect(page.locator('#time-value')).toHaveText('0.240 s');
  await expect(page.locator('#chart-note')).toContainText('Other body geometry is fixed');
  await page.screenshot({path:'test-results/garment-contact-tissue-inspection.png',fullPage:true});
  await page.locator('#garment-shorts').check();
  await page.locator('#regional-study').selectOption('body');
  await expect(page.locator('#garment-contact-monitor')).toBeHidden();
  await expect(page.locator('#trajectory-run')).toBeEnabled();
  await expect(page.locator('#garment-shirt')).toBeChecked();await expect(page.locator('#garment-shorts')).toBeChecked();
  expect(errors).toEqual([]);
});

test('late contact response cannot replace a subsequently selected whole-body view',async({page,request})=>{
  const response=await request.get('/api/body/experiments/garment-contact'),data=await response.json();
  let release,reached=false;const gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/api/body/experiments/garment-contact',async route=>{reached=true;await gate;await route.fulfill({json:data});});
  await page.goto('/');await expect(page.locator('#model')).toHaveValue('ihm-body');
  await page.locator('#regional-study').selectOption('garment-contact');await expect.poll(()=>reached).toBe(true);
  await expect(page.locator('#play')).toBeDisabled();
  await page.locator('#regional-study').selectOption('body');release();
  await expect(page.locator('#garment-contact-monitor')).toBeHidden();
  await expect(page.locator('#regional-study')).toHaveValue('body');
  await expect(page.locator('#flow-legend')).not.toContainText('panel');
});
