import {test,expect} from '@playwright/test';

test('body-attached contact and non-neural voltage materializations use computed fields',async({page,request})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.locator('#model')).toHaveValue('ihm-body');
  await page.getByLabel('Active materialization',{exact:true}).selectOption('forearm-touch');
  await expect(page.locator('#details h2')).toHaveText('Forearm contact & sensation',{timeout:30000});
  await expect(page.locator('#play')).toBeEnabled();
  await page.locator('#time').fill('100');await page.locator('#time').dispatchEvent('input');
  await expect(page.locator('#flow-legend')).toContainText('100.0 µm');
  await expect(page.locator('#time-value')).toHaveText('0.200 s');
  await page.getByLabel('Active materialization',{exact:true}).selectOption('skin-electric');
  await expect(page.locator('#details h2')).toHaveText('Non-neural skin electricity');
  await expect(page.locator('#view-title')).toHaveText('Skin · non-neural electricity');
  await expect(page.locator('#render-count')).toHaveText('9 membrane sites · 9 apical sites');
  await page.locator('#time').fill('40');await page.locator('#time').dispatchEvent('input');
  await expect(page.locator('#flow-legend')).toContainText('92.74 V/m');
  await page.getByLabel('Regional electrical intervention').selectOption('baseline');
  await page.locator('#time').fill('40');await page.locator('#time').dispatchEvent('input');
  await expect(page.locator('#flow-legend')).toContainText('0.00 V/m');
  await page.getByLabel('Regional electrical intervention').selectOption('electrode');
  await page.screenshot({path:'test-results/regional-electric.png',fullPage:true});
  await page.getByLabel('Active materialization',{exact:true}).selectOption('body');
  await expect(page.locator('#regional-condition')).toBeHidden();
  await page.locator('#tab-spectral').click();
  await page.getByLabel('Spectral representation').selectOption('laplace');
  const temporal=await (await request.get('/api/temporal')).json();
  const runId=await page.locator('#spectral-run').inputValue();
  const run=temporal.runs.find(r=>r.id===runId)||temporal.runs[0];
  await expect(page.locator('#sigma option')).toHaveText(run.laplace.sigma_per_s.map(s=>`σ = ${s} s⁻¹`));
  await expect(page.locator('#chart svg')).toBeVisible();
  await page.getByLabel('Active materialization',{exact:true}).selectOption('skin-electric');
  await expect(page.locator('#details h2')).toHaveText('Non-neural skin electricity');
  await page.locator('.view-section').filter({hasText:'Sources & body status'}).evaluate(el=>el.open=true);
  await page.locator('#source-inspection summary').click();
  const source=await page.locator('#model option').evaluateAll(options=>options.find(o=>o.value!=='ihm-body').value);
  await page.locator('#model').selectOption(source);
  await expect(page.locator('#trajectory-run')).toBeEnabled();
  await expect(page.locator('#spectral-run')).toBeEnabled();
  await expect(page.locator('#signal-source')).not.toContainText('non-neural RC');
  expect(errors).toEqual([]);
});
